from pwn import *
"""
rand() function is not unpredictable.
Value of the rand() was not predicted, cause there is a pseudo randomization.
rand() just generates a vector of values and then take one from it. BUT.
The vector doesn't change.
To solve this you need open it in gdb and then set a breakpoint in which you can see the 'random' value.
"""


def exploit():
    # ssh connection
    s = ssh(user='random', host='pwnable.kr', password='guest', port=2222)
    # Our key that will xor with upredictable random value
    key = str(3039230856)
    p = s.process('./random')
    p.sendline(key)
    print(p.recvall())
    p.close()


if __name__=='__main__':
    exploit()
